services:
  ctf-idor:
    build: ./01-idor-waf
    ports:
      - "3003:3003"
    container_name: ctf-idor
    networks:
      - ctf-network
    
  ctf-jwt:
    build: ./02-jwt_injection
    ports:
      - "3007:3007"
    container_name: ctf-jwt
    networks:
      - ctf-network
    
  ctf-information-disclosure:
    build: ./03-information_disclosure_AND_weak_crypto
    ports:
      - "3010:3010"
    container_name: ctf-information-disclosure
    networks:
      - ctf-network

networks:
  ctf-network:
    driver: bridge
